replicaCount: 1

image:
  repository: aadbccd8-cute-cygnus.registry.twcstorage.ru/teachers-bot-v2
  pullPolicy: Always
  tag: ""

env:
  - name: BOT_TOKEN
    value: "your-bot-token-here"
  - name: TEACHERS_API_URL
    value: "http://teachers-api"
  - name: REDIS_HOST
    value: "redis"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_DB
    value: "0"
  - name: RABBITMQ_URL
    value: "amqp://guest:guest@rabbitmq:5672/"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Bot doesn't need service or ingress as it connects to Telegram API
service:
  enabled: false

ingress:
  enabled: false