apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: api-app
build:
  local:
    push: false
  tagPolicy:
    customTemplate:
      template: "latest"
  artifacts:
  - image: scrapers-api
    context: scrapers-api
    docker:
      dockerfile: Dockerfile
  - image: profi-scraper
    context: profi-scraper
    docker:
      dockerfile: Dockerfile
  - image: notification-bot
    context: notification-bot
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: scrapers-api
      chartPath: scrapers-api/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - scrapers-api/.helm/values.yaml
    - name: notification-bot
      chartPath: notification-bot/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - notification-bot/.helm/values.yaml

portForward:
- resourceType: service
  resourceName: scrapers-api-service
  namespace: default
  port: 80
  localPort: 8000
