apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: api-app
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/scrapers-api
    context: scrapers-api
    docker:
      dockerfile: Dockerfile
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/profi-scraper
    context: profi-scraper
    docker:
      dockerfile: Dockerfile
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/notification-bot
    context: notification-bot
    docker:
      dockerfile: Dockerfile
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/teachers-api
    context: teachers-api
    docker:
      dockerfile: Dockerfile
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/teachers-bot-v2
    context: teachers-bot-v2
    docker:
      dockerfile: Dockerfile
  - image: aadbccd8-cute-cygnus.registry.twcstorage.ru/lesson-checker
    context: lesson-checker
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: scrapers-api
      chartPath: scrapers-api/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - scrapers-api/.helm/values.yaml
    - name: notification-bot
      chartPath: notification-bot/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - notification-bot/.helm/values.yaml
    - name: frontend
      chartPath: frontend/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - frontend/.helm/values.yaml
    - name: lesson-checker
      chartPath: lesson-checker/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - lesson-checker/.helm/values.yaml
    - name: teachers-api
      chartPath: teachers-api/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - teachers-api/.helm/values.yaml
    - name: teachers-bot-v2
      chartPath: teachers-bot-v2/.helm
      namespace: default
      createNamespace: true
      valuesFiles:
        - teachers-bot-v2/.helm/values.yaml

portForward: []