replicaCount: 1

image:
  repository: aadbccd8-cute-cygnus.registry.twcstorage.ru/frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8501

ingress:
  enabled: true
  host: ""  # Пустой хост - будет работать с любым IP

resources:
  requests:
    cpu: 0.1
    memory: 128Mi
  limits:
    cpu: 0.2
    memory: 256Mi

secrets:
  SCRAPERS_API_BASE: "http://scrapers-api-service"