apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  auth: eXAwcVo2aE1LT2RKM2ZUOiRhcHIxJHllZ3JPSWRFJHE2ZG42NDBKeEY2M1JtWlI1a1VRMy8=

