apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.secrets.DATABASE_USER | b64enc }}
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD | b64enc }}
  DATABASE_HOST: {{ .Values.secrets.DATABASE_HOST | b64enc }}
  DATABASE_PORT: {{ .Values.secrets.DATABASE_PORT | b64enc }}
  DATABASE_NAME: {{ .Values.secrets.DATABASE_NAME | b64enc }}
  RABBITMQ_USER: {{ .Values.secrets.RABBITMQ_USER | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.RABBITMQ_PASSWORD | b64enc }}
  RABBITMQ_HOST: {{ .Values.secrets.RABBITMQ_HOST | b64enc }}
  RABBITMQ_PORT: {{ .Values.secrets.RABBITMQ_PORT | b64enc }}

