replicaCount: 1

image:
  repository: aadbccd8-cute-cygnus.registry.twcstorage.ru/lesson-checker
  pullPolicy: Always
  tag: "latest"

resources:
  requests:
    cpu: "0.1"
    memory: "128Mi"
  limits:
    cpu: "0.2"
    memory: "256Mi"

# CronJob настройки
cronjob:
  schedule: "*/15 * * * *"  # Каждые 15 минут
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  restartPolicy: OnFailure
  backoffLimit: 3

# Переменные окружения
env:
  NOTIFICATION_QUEUE: "lesson_notifications"

# Секреты
secrets:
  DATABASE_HOST: "192.168.0.9"
  DATABASE_PORT: "5432"
  DATABASE_USER: "gen_user"
  DATABASE_PASSWORD: "dG^,+Rx3Waf,3w"
  DATABASE_NAME: "default_db"

  RABBIT_HOST: "my-release-rabbitmq"
  RABBIT_PORT: "5672"
  RABBIT_PASSWORD: "J8lqS07OcSLYvLGd"
  RABBIT_USER: "user"
  RABBIT_QUEUE: "scrapers"


