apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.apiService.port }}
  type: ClusterIP