replicaCount: 1

image:
  repository: aadbccd8-cute-cygnus.registry.twcstorage.ru/teachers-api
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: teachers-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  API_HOST: "0.0.0.0"
  API_PORT: "8080"

  DATABASE_HOST: "192.168.0.9"
  DATABASE_PORT: "5432"
  DATABASE_USER: "gen_user"
  DATABASE_PASSWORD: "dG^,+Rx3Waf,3w"
  DATABASE_NAME: "default_db"

  RABBIT_USER: "user"
  RABBIT_PASSWORD: "J8lqS07OcSLYvLGd"
  RABBIT_HOST: "my-release-rabbitmq"
  RABBIT_PORT: "5672"
  RABBIT_QUEUE: "scrapers"

  TINKOFF_TOKEN: "TBankSandboxToken"


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}